### ISSUE TITLE
Some issues about colorization

### ISSUE THREAD

**Issue by dehghani-mehdi** [mrmlnc/vscode-vash#1]
Hi,

Thanks for your great extension.

I just tested the extension and here is result, imagine following block of code:

```
@html.extend("layout", function(model) {
    @html.block("body", function(model) {
        <div id="my-id" class="my-class">
            @html.include('SOME_PARTIAL', {
                content: model.X
            })
        </div>
    })
})
```
- Seems like colorization for all `keywords` works perfectly, (_by keyword, I mean javascript keyword_)
- For `@html` (Vash) keyword, colorization doesn't work but for very first one.
- Colorization doesn't work for `HTML` tags (of course works for `id` & `class` words)
- Colorization works for all `string` values, but `include`'s param (in above ex. `SOME_PARTIAL`)

I using latest version of `VSCode`, also using default dark theme.

**Comment by mrmlnc** [comment]
@MehdiDehghani, I'll start working on this soon.

**Comment by mrmlnc** [comment]
@MehdiDehghani,

Please, try new version of this extension and let me know if something is wrong.

Brackets highlight is not this extension.

![image](https://cloud.githubusercontent.com/assets/7034281/18151187/f6dac4e4-6ff5-11e6-8e4f-26787f078bcf.png)

**Comment by dehghani-mehdi** [comment]
@mrmlnc amazing man, looks like everything works perfectly. thanks !!
I'm wondering, can I change color of `@KEYWORD`? I'm asking this, because in default theme this guys shown in `blue` just like `HTML` tags.

**Comment by dehghani-mehdi** [comment]
I'm just found out another small issue still alive, check out the screenshot please.

![vash](https://cloud.githubusercontent.com/assets/9152330/18154825/443d3c36-701d-11e6-9cd6-226bb46d0e72.png)

**Comment by mrmlnc** [comment]
@MehdiDehghani,

> I'm wondering, can I change color of @KEYWORD

Nope, it depends on used theme. 

![2016-09-01_11-17-42](https://cloud.githubusercontent.com/assets/7034281/18160355/c1f06ab4-7035-11e6-822e-81f856b4fc53.gif)
