### ISSUE TITLE
[Feature request] Add formatting support

### ISSUE THREAD

**Issue by dehghani-mehdi** [mrmlnc/vscode-vash#2]
Hi,

I don't if you have plan for adding this feature to your extension or not, but if you add this feature, will be great.

Thank you !

**Comment by mrmlnc** [comment]
Hmm, I think that it related to reindentation of code?

**Comment by dehghani-mehdi** [comment]
For now, `.vash` is not supported by any of formatter extensions and VSCode itself.
I tired to add `.vash` to `HTML` (using VSCode user setting file), but the result become unreadable after formatting, as the `vash blocks` isn't `HTML`.
Hope I could say the point.

**Comment by dehghani-mehdi** [comment]
Seems like this issue should be closed as I don't use VSCode anymore. many thanks @mrmlnc
