### ISSUE TITLE
Intellisense for helpers

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-vash#3]
I think that users would like to get this opportunity.

@MehdiDehghani, what do you think?

**Comment by dehghani-mehdi** [comment]
@mrmlnc  Oh man, that's awesome. I'm looking forward to this lovely feature !!

**Comment by mrmlnc** [comment]
@MehdiDehghani, I added a very simple code completion. I wrote out all the methods for `@html`, which are described in the Vash documentation. Some methods in the documentation do not have explicit links to `@html`.

![2016-09-01_20-00-39](https://cloud.githubusercontent.com/assets/7034281/18176576/d0328a5a-707e-11e6-99ea-a90cbe71b3f3.gif)

If you have time maybe you could supplement the current list ([lib/helpersList.json](https://github.com/mrmlnc/vscode-vash/blob/master/lib/helpersList.json)). Or provide short description for the already existing methods.

Also I'll work on the autocompletion that is based on the function parameters.

**Comment by dehghani-mehdi** [comment]
@mrmlnc Amazing, really helpful.

About `helpersList.json`, did you mean I complete `details`  section by copy relevant description from [Vash page](https://github.com/kirbysayshi/vash)?

**Comment by mrmlnc** [comment]
@MehdiDehghani, IMO, need to shorten the description. For example,

``` json
{
  "label": "raw",
  "details": "By default, all content that passes from a model to a template is HTML encoded. This method passes content without HTML encoded.",
  "documentation": "@html.raw(text: string)"
}
```

**Comment by mrmlnc** [comment]
Done.

![2016-09-02_12-51-02](https://cloud.githubusercontent.com/assets/7034281/18200111/f023f3a2-710b-11e6-8e47-dd9de412590c.gif)

**Comment by dehghani-mehdi** [comment]
Great man, thanks for adding this feature.

I just wanna commit my changes btw, but that's okay, now is better that you completed the file by yourself.

Looking fwd to more features.

**Comment by mrmlnc** [comment]
@MehdiDehghani, you can provide example for https://github.com/mrmlnc/vscode-vash/blob/master/lib/helpersList.json#L12-L16?
